### ISSUE TITLE
After showing the warning of the existent profile, the addon doesn't work

### ISSUE THREAD

**Issue by ivnc** [lambda-nvda/lambdaNvda#17]
Steps to reproduce:
1. Update or re-install the addon.
2. You'll see a warning saying that a profile called "lambda" is already present.
3. After pressing ok, the status of the addon continues on "install", instead of "running".
The solution I found is to delete the lambda profile and to reinstall the addon.

**Comment by nvdaes** [comment]
Hi, I can't reproduce the reported bug.
Time ago I got this error, but I don't know on what depends. I deleted 
the pending install add-on and now all is right.
Thanks.

**Comment by nvdaes** [comment]
Hi, the bug on pending installation can be produced when Lambda add-on, 
that is, with the first character capitalized, when the add-on name 
wasn't complain with add-on guidelines, is installed and we try to 
install lambda-1.3.
Thanks.

**Comment by albzan** [comment]
Unfortunately this can't be fixed since the two addons are considered as different addons (with a different name).
I think that the problem may occurs since the path is the same (case insensitive).

**Comment by albzan** [comment]
Not confirmed, btw a solution will be provided

**Comment by albzan** [comment]
Hi Ivan,

I solved adding a popup message during the installation, asking the user to uninstall the previous version.

Could you translate it please?

Thank you,

Cheers,

Alberto.

**Comment by ivnc** [comment]
Done. Thanks for the alert.
