### ISSUE TITLE
When typing in the Lambda math text box and writing the character nº 55 in the same line, NVDA stops reading character by character(NVDA+2)

### ISSUE THREAD

**Issue by ivnc** [lambda-nvda/lambdaNvda#22]
Steps to reproduce:
1. Turn on character-by-character reading.
2. Start typing some random expression as detailed in the attached lambda file.
3. About the character nº 55, NVDA stops reading the text. However, if I continue typing to keep away from the character 55 and I delete some characters NVDA wil temporalily read the text correctly.
Note: it only affects to the character-by-character reading mode.

It happens both with mathematic and with text expressions. Also the selection has a strange behavior.

Attached a template to do easier the testing, view it [here(zip)](https://github.com/nvdaaddons/lambda/files/512076/demostracion_y_plantilla_error_complemento_lambda_nvda.zip)

Any problem please comment.

Regards.

**Comment by albzan** [comment]
Hi,
Thank you for your feedback!
Could you please try with the latest dev (1.1.4)?
Regards,
Alberto

**Comment by ivnc** [comment]
Oh, you are back again, nice notice, I thought that you were dead. Tomorrow I'll make the tests as requested with the latest development version of the addon. I'll post the results once the tests were finished.

regards.

**Comment by ivnc** [comment]
Fixed with current version. Thanks.
