### ISSUE TITLE
Feature request: add sixdots.exe on profile triggers by default

### ISSUE THREAD

**Issue by ivnc** [lambda-nvda/lambdaNvda#31]
By doing this, the 6-dot braille would be correctly translated using the already present 8-dot LAMBDA braille table. The only thing to do in order to implement this is to add "sixdots.exe" onto the trigger list for the LAMBDA profile.
The spanish braille table works as expected in the initial tests, so I think that on a few days we could have it ready and properly tested.

Regards.

**Comment by albzan** [comment]
Hi,
Ok! I'll do it.

Really? Do You have the sixdots.exe? This file seems to be disappeared from the Italian Lambda distribution.... I need to investigate why...
Alberto

**Comment by ivnc** [comment]
When pressing F2 to open the 6-dot view mode sixdots.exe is executed.
In fact, if I go to NVDA>Configuration Profiles>Trigger I can see:
"Current application: sixdots.exe", "Default Configuration". I've
changed it to use the "lambda" profile, but I think that it should be
implemented by default.

**Comment by albzan** [comment]
Yes,
What I was wondering was why you have the sixdots.exe and I don't have it in my installation. I.e. when I press F2 nothing's happening. Smile

**Comment by ivnc** [comment]
Yes, that's really strange... I'm working with the last version and on all LAMBDAs I saw the option was present.

**Comment by ivnc** [comment]
Just a quick update on this.

A few months ago I changed my PC: The regional administration gave me a new one and I installed windows 10 and Lambda 1.44 from lambdaproject.org.

I discovered that, as you said, sixdots.exe was not present, and that nor F2 nor the menu option worked. I made several contacts trying to clarify this and I've received the following responses:
Veia Progetti says that the function was deleted since LAMBDA 1.40 (non inclussive) and that I should have a very old version in order to have sixdots working.
-Many Tiflotechnology specialists from ONCE agreed with the Veia's point, saying that the function was removed.
-But, an user reported that her ONCE's specialist replaced some files of LAMBDA 1.44 and it worked.
The definitive response is from José Enrique, who commented the following:
1. Veia removed the files from the installer, but *not* from existing LAMBDA 1.40 or previous versions installations. So if you update from LAMBDA 1.40 to LAMBDA 1.44 the conversion should continue working.
2. The solution he proposes is to add missing files to clean 1.44 installations. I suppose that installing 1.40 and then 1.44 should also work. Don't forget to deactivate the license before attempting this operations, I lost mine a few times doing tests.
3. But, for me, this didn't work. Jose Enrique send me the files, I put them and pressing f2 didn't open some dialog. I suppose that they deleted the files to not adapt the sixdots to newer OS releases (because I can use, with LAMBDA 1.44, the conversion in my old XP laptop), but I'm not absolutely sure. I'm waiting for José Enrique's response.

This is a comment to try to clarify the doubts existent about the sixdots.exe. The deletion was not exclussive of the Italian package, is for all languages. If someone were interested I could post updates on this here, but it's not a question strictly related with LAMBDA and NVDA.
So you were right. Sixdots was deleted, officially.
Anyway sixdots.exe on the triggers adds compatibility with old versions with this feature or with users' LAMBDAs with the feature patched successfully.
A LAMBDA 1.40 installer can be got from ftp://anonymous@ftp.once.es/pub/utt/tiflosoftware/Miscelanea/LambdaSetup140.zip

**Comment by JuanMSK** [comment]
hola. estoy buscando el instalador de lambda 1.40 para ver si con el anda la tecla f2. Alguien tiene para poder descargarlo? el link que publicaron ya esta caido.
 ftp://anonymous@ftp.once.es/pub/utt/tiflosoftware/Miscelanea/LambdaSetup140.zip

**Comment by ivnc** [comment]
La ONCE ha dejado de comercializar LAMBDA, motivo por el cuál supongo 
que no estará disponible.

La última versión puede encontrarse en: 
http://veia.it/sites/all/files/lambda/1440_19/LambdaSetup144.exe

Por favor, intenta no utilizar incidencias para plantear cuestiones de 
soporte. En la ayuda del complemento hay referencias al grupo en inglés 
y en la propia comunidad hispanohablante tenemos varios lugares de 
discusión, entre ellos varias listas de correo abiertas.


Saludos.

**

ONCE has stopped LAMBDA distribution, so I suppose that's the reason why 
it isn't available now.

Last version can be found at: 
http://veia.it/sites/all/files/lambda/1440_19/LambdaSetup144.exe

Please, try not to use issues to address support concerns. There are 
some references in the documentation to the English mailing list and on 
the Spanish-speaking Community there are several discussion places, 
within them many open mailing lists.


Regards.
