### ISSUE TITLE
Last unselected character is not spoken

### ISSUE THREAD

**Issue by nvdaes** [lambda-nvda/lambdaNvda#36]
STR:
1. Open The Lambda editor and write some text.
2. Select them and press shift+left arrow.

Expected:
The last unselected character should be announced.

**Comment by albzan** [comment]
This depends on the Lambda COM Object that returns null (it doesn't support unselected). Can't be easily fixed.

**Comment by nvdaes** [comment]
OK. The spanish table seems to work fine. I can review the last
changes and when you want we can post this for a wide testing on the
website.
Just let us know if you're planning to manage translations from the
community system, so that al the NVDA translators can help, or if you
prefer that people send PR to GitHub.
If you want to manage this from the community, the normal procedure is
to wait about two weeks with the add-on posted on the website, and
then you would declare it stable, I or another person create a repo on
Bitbucket for translations, we register the add-on on Exbi server, and
each week sent translations will be updated. Then you can merge it in
the add-on and release versions.


2017-05-17 14:29 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Hi Noelia,
Try the implementation in the branch bug36.
I think it should be easier. I've done some testing and it seems to work. Can you test? What do you think?
Alberto

**Comment by nvdaes** [comment]
Oh great! Please implement bug36 branch.
Though when I press shift+end, the selected text is spelled.
Cheers

2017-05-18 9:37 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Hi Noelia,
I don't understand.
Have you experienced bugs?
I've tried this:
1. I wrote 3+4-5=0
2. Press home
3. Press shift+end
4. press right arrow
The speech doesn't report nothing. It's the same for you?
Thanks,
Alberto

2017-05-18 10:32 GMT+02:00 nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Yes, it's the same. Just I wonder if spelling in Lambda can be
suppressed sometimes.

2017-05-18 10:42 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Hi Noelia,
Ah, Ok! Great!
Yes, you can go to Options - Speech Options and select "Mute" radio button.
In this way you have the editor control muted but menus and dialogs are
correctly spoken.
Alberto

2017-05-18 11:21 GMT+02:00 nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
t the add-on when you want.Oh, great.
I'm wishing to pos

2017-05-18 11:41 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Ok,
Do you like the new message while a conflicted profile is present? See
installTasks.py

2017-05-18 12:10 GMT+02:00 nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
I see later and comment.
Please take care about config writen on secure screens.

2017-05-18 12:39 GMT+02:00, albzan <notifications@github.com>:

**Comment by albzan** [comment]
Lambda has no service so it can't be run on secure desktop
Alberto

2017-05-18 12:43 GMT+02:00 nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Ah, great. Then all is perfect to post the add-on.
Please merge braille table of Spanish and when you want I will proceed.
This is a wanderful add-on. Hope I had know and use Lambda time ago.
Thanks.

2017-05-18 12:47 GMT+02:00, albzan <notifications@github.com>:

**Comment by nvdaes** [comment]
Hi, install tasks message about profiles is fine. Copyright is 2016
and I see double # in comments, etc., but code is right.
Thanks.

2017-05-18 12:43 GMT+02:00, nvdaes <notifications@github.com>:
